Story/utf 4427 enable ahs cas
Silabs-UTF/terraform-provider-hwmux pull request #41
Opened 2024-01-05 15:10 UTC by austinhallett

Updates to the newest version of the hwmux golang client sdk, and adds `enable_ahs_cas` flag to device group data source

2024-01-05 16:40 UTC, panargirakis requested changes
In devicegroup_resource.go there are functions that convert the plan to an API request and the other way around. You need to update those to handle the new field.

2024-01-05 16:40 UTC, panargirakis commented on hwmux/devicegroup_data_source.go
> +	// data.Enable_ahs_cas = types.BoolValue(deviceGroup.GetEnableAhsCas())
Is this commented out on purpose?

2024-01-05 16:56 UTC, austinhallett commented on hwmux/devicegroup_data_source.go
> +	// data.Enable_ahs_cas = types.BoolValue(deviceGroup.GetEnableAhsCas())
resolved

2024-01-17 18:06 UTC, panargirakis approved these changes

2024-01-17 18:09 UTC, merged