Adding source to all the model and resources
Silabs-UTF/terraform-provider-hwmux pull request #42
Opened 2024-07-25 15:20 UTC by Avijitsingh19021999

2024-07-25 15:52 UTC, panargirakis requested changes
I don't think we should make the `source` field user-controllable. We need a way to make this read-only in the schema.

2024-07-25 15:52 UTC, panargirakis commented on examples/full-example/main.tf
> +  source            = "TERRAFORM"
We don't want to instruct users to set this field since we want it to stay as a default. So let's remove it from the example.

2024-07-25 15:52 UTC, panargirakis commented on go.mod
> +	github.com/Silabs-UTF/hwmux-client-golang/v2 v2.0.0-beta.10
definitely need a non-beta version before we go to production

2024-08-01 08:46 UTC, Avijitsingh19021999 commented on go.mod
> +	github.com/Silabs-UTF/hwmux-client-golang/v2 v2.0.0-beta.10
As soon as I merge the changes with black=true. I will generate a latest client and use it for production.

2024-08-01 14:57 UTC, panargirakis approved these changes

2024-08-21 15:49 UTC, panargirakis commented on go.mod
> +	github.com/Silabs-UTF/hwmux-client-golang/v2 v2.0.0-beta.10
Is this done?

2024-08-22 13:49 UTC, merged